server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  # h2 DB, 웹 설정 및 셋팅
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  # Properties 파일 - Thymeleaf 설정
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
